name: Security Scan

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run weekly on Sundays at 2 AM UTC
    - cron: '0 2 * * 0'

jobs:
  security-scan:
    name: Security Analysis
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        npm install
        pip install detect-secrets pre-commit

    - name: Run npm audit
      run: |
        npm audit --audit-level=moderate
      continue-on-error: true

    - name: Run detect-secrets scan
      run: |
        detect-secrets scan --baseline .secrets.baseline --force-use-all-plugins

    - name: Run pre-commit hooks
      run: |
        pre-commit install
        pre-commit run --all-files
      continue-on-error: true

    - name: Scan for hardcoded secrets
      run: |
        echo "Scanning for potential secrets..."
        if grep -r "ghp_" --exclude-dir=.git --exclude="*.md" .; then
          echo "::error::GitHub token pattern found!"
          exit 1
        fi
        if grep -r "sk-" --exclude-dir=.git --exclude="*.md" .; then
          echo "::error::OpenAI API key pattern found!"
          exit 1
        fi
        echo "No hardcoded secrets detected."

    - name: Upload security scan results
      uses: github/codeql-action/upload-sarif@v2
      if: always()
      with:
        sarif_file: results.sarif
      continue-on-error: true